export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS'
export const FETCH_AUTH_USER_FAIL = 'FETCH_AUTH_USER_FAIL'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const INCRESEQUANTITY = 'INCRESEQUANTITY'
export const DECREASEQUANTITY = 'DECREASEQUANTITY'
export const RESET_ITEMS = 'RESET_ITEMS'