export const FETCH_AUTH_USER_SUCCESS = 'FETCH_AUTH_USER_SUCCESS'
export const FETCH_AUTH_USER_FAIL = 'FETCH_AUTH_USER_FAIL'


export const GET_CART = 'GET_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
export const INCRESEQUANTITY = 'INCRESEQUANTITY'
export const DECREASEQUANTITY = 'DECREASEQUANTITY'
export const RESET_ITEMS = 'RESET_ITEMS'

export const CREATE_BUY_CART = 'CREATE_BUY_CART'
export const RESET_CART = 'RESET_CART'

export const FETCH_BRAND = 'FETCH_BRAND'
export const FETCH_CATEGORY = 'FETCH_CATEGORY'
export const FETCH_BEST_SELLER = 'FETCH_BEST_SELLER'
